# Consider the Audience

When we create data visualizations to present quantitative information, instead of jumping straight to the designing stage, we should first understand "the context for the need to communicate" [Knaflic, 2015, p. 18]. The context can be split into two parts: the target audience and the intended message.

## Who is the Audience

**1. What is their role? What is their background?**  

Actuaries can use different kinds of visualizations to communicate actuarial findings and recommendations to various groups such as fellow actuaries, regulators, underwriters, brokers, executives and many more. A common pitfall is that we tend to generalize the target audience group to "internal and external stakeholders" or "anyone who may be interested" [Knaflic, 2015, p. 21]. These generic groups include audiences with different roles and backgrounds, so it's more difficult to accomodate the different interests and perceptions of the visualizations, and possibly result in mis-use or mis-interpretation of the visualization. 

We must tailor the visualizations to a specific audience group to maximize the effectiveness of the message. In order to narrow the target audience group, Knaflic recommends identifying the decision maker topic at hand. Ask yourself: what information and what considerations drive the decision-maker"? Asking yourself "Who the audience" is may also determine whether the presentation should be live/interactive or whether it is appropriate to send the audience the visuals to view on their own.

**2. How technical are they? What do they already know?**  

After defining the target audience group, the presenter should learn the audience's technical knowledge level. Actuarial analyses can be too technical and difficult to comprehend for non-actuarial groups, especially with the large collection of actuarial acronyms, terms and methods. When designing a visualization for non-actuarial audience, consider putting yourself in their shoes by asking yourself "what is their perspective?" and "what do they know?". The same is true for actuarial audiences; they will understand and absorb the information more effectively if it is presented simply, with their knowledge level in mind, no matter how technical the material.

## What is the Message

When crafting visuals, a content creator should continually ask themselves and fellow workers "What is the message?". Asking this question and other related questions below helps refine the content, complexity, and nature of visual presentations.

**1. What does the audience need know to influence the decision?**  

After we are familiarized with the target audience's role and technical background, we should think about how to make the visualization relevant for the audience. In other words, what information needs to be included in the visualization to help the audience make decision. Knaflic clarifies an important disctinction between exploratory analysis and explanatory analysis. Exploratory analysis refers to the preliminary work we do "to understand the data and figure out what might be noteworthy or interesting to highlight to others" [Knaflic, 2015, p. 19], and explanatory analysis refers to the "specific thing you want to explain" or the "specific story you want to tell" [Knaflic, 2015, p. 20]. We should focus on the **explanatory** aspect of our work in the visualizations to influence the audience's decision. For example, an underwriter may rather see how a change in selected tail factor affects the bottom line loss ratio, whereas another actuary may want to see all the indicated tail factors underlying the change in selected tail factor. Think about what motivates your audience.

**2. How much detail do they really need? How much will suit them?**  

According to Knaflic, the communication mechanism determines how much control the presenter has on how the target audience consumes the information, which in turn determines the level of detail a visualization needs [Knaflic, 2015, p. 23]. For example, during a live presentation, the presenter has the most control over the flow of the storytelling process. If the audience has question about a particular point, the presenter can answer right away and provide more details in person, so the **visualizations in the presentation deck do not need to be over-filled with details**. However, for written documents like emails and reports, the presenter has less control on when and how the audience will interpret the visualization, so even more consideration and careful thought may be needed in creating visualizations, to communicate the intended message. Our tendency may be to provide more detail, but that may confuse rather than clarify the message.

**3. What is the audience supposed to DO with the information?**  

It's important to remember that after we inform the audience about the problem and key insights, we should guide them to take actions to resolve the problem. We can explicitly state the next steps, provide recommendations, or encourage discussions for situations where next step is unclear [Knaflic, 2015, p. 22]. It is reasonable to include an action statement _within_ the title or visual, however.
