# Conclusion

With these basic principles and examples, you can start creating impactful, sleek, modern data visualizations that convey your message effectively.

Think about your audience, what they know, and what they _need_ to know. Keep asking yourself and others **“What’s the Message?”** throughout the data visualization design process. Your focus should be on identifying and displaying those things that best convey the message to your intended audience.

Use the visualization that matches the type of data and message. Line graphs are good for time series and (smoothed) distributions. Bar graphs have many uses, including comparing values by category, and parts-to-a-whole with stacked bars. Use horizontal bar graphs when the data labels are long, since we read horizontally (not vertically, or on a 45-degree angle).

Declutter visualizations, by removing extraneous axis lines, tickmarks, borders. Remove everything that does not help tell the message, or use gray font or line/bar color to de-emphasize non-essential elements. Let the data itself be the star of the show.

Accentuate the data so your message pops out for your audience. Draw attention to the most important data using length, width, shape, color, and other techniques to distinguish the data and highlight the message. Use Preattentive Attributes when designing your visualization (use length and relative position in 2D, rather than area and volume, for example). Use Gestalt principles, which reflect the science of how the human eye perceives lines, bars, dots, etc. in space.

Be creative and have fun creating data visualizations that enlighten your audience and convey your message!

# Acknowledgements {-}

This paper comes from the work and discussions of the CAS Data Visualization Working Party. The membership is comprised of the following individuals:

```{r}
tibble::tibble(
  member = c(
    'Damian Bailey'
  , 'Julian Coleman'
  , 'John Deacon'
  , 'Marc-Andre Desrosiers'
  , 'Chunyang Fan'
  , 'Brian A. Fannin'
  , 'Navarun Jain'
  , 'Benyamin Kosofsky'
  , 'Clifford Lau'
  , 'Jennifer Levine' 
  , 'Khanh Luu'
  , 'Madeline Main' 
  , 'Paul Majchrowski'
  , 'Paul Mayfield'
  , 'Sameer Nahal'
  , 'Bradford Nichols'
  , "Brian O'Reilly"
  , 'David Payne'
  , 'Keith Quigley'
  , 'Tanveer Quraishi'
  , 'Kyle Reed'
  , 'Rajesh Sahasrabuddhe'
  , 'Raymond Tobias'
  , 'Karthik Tumuluru' 
  , 'Jeffrey White'
  , 'Patrick Yu'
  , 'Arthur Zachary'
  )
) %>% 
  knitr::kable()
```


